### ISSUE TITLE
尝试将该程序改为app端报错 非法請求

### ISSUE THREAD

**Issue by doveppp** [wearzdk/macaoapply-auto#11]
其他的都没什么问题，就是最后的时候返回值为
createPassAppointment接口返回
{'responseCode': 700, 'responseResult': None, 'responseMessage': '非法請求，請重新進入通關預約服務'}
是不是验证码那里有问题？

**Comment by wearzdk** [comment]
之前我遇到这种情况的原因是没有按顺序来访问接口，你可以对照抓包检查一下app端有没有进行一些其他操作。

验证码应该会有个检查验证码的接口，这个通过了应该没大问题。

**Comment by doveppp** [comment]
感谢 可以了
